### ISSUE TITLE
f5acmehandler.sh script does not provide an option to sync configuration in HA environment

### ISSUE THREAD

**Issue by joebride** [f5devcentral/kojot-acme#2]
Hallo!

#### Description  
The ```f5acmehandler.sh```  utility script does not provide to sync configuration from Active- to Standby-LB if there was an update to certificate/private key/chain.
This would be very useful to prevent configuration inconsistency when a failover was triggered and the cron-scheduled process is running several hours later!

#### Expected Result
Please provide an option to sync configuration from Active- to Standby-LB if there was a change.

Many Thanks!

**Comment by joebride** [comment]
Hello!
Any update on this? THX!

**Comment by kevingstewart** [comment]
Added **FORCE_SYNC** and **DEVICE_GROUP** options in the per-domain config file to enable force HA synchronization when any of the following have changed:

- Certificate renewals
- Account information (registration)
- Config information
