### ISSUE TITLE
install.sh script variable "f5acmehandler_url" is still referencing kevingstewart/simple-dehydrated-acme repository

### ISSUE THREAD

**Issue by vsnine** [f5devcentral/kojot-acme#3]
install.sh script variable "f5acmehandler_url" is still referencing kevingstewart/simple-dehydrated-acme repository instead of the f5devcentral/kojot-acme repository.

https://github.com/f5devcentral/kojot-acme/blob/194428ff07fda0ca31cf5acb6cb0127f180c0f96/install.sh#L17

**Comment by kevingstewart** [comment]
Resolved.
